//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lekarstv
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Form { get; set; }
        public string Dozirovka { get; set; }
        public string Proizvod { get; set; }
        public string Date { get; set; }
    }
}
