//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nalich
    {
        public int id { get; set; }
        public string id_lekarstv { get; set; }
        public string id_apteki { get; set; }
        public string kol_vo { get; set; }
        public string price { get; set; }
    }
}
